web:
  build: .
  ports:
   - "5000:5000"
  volumes:
   - .:/code
  links:
   - redis
queue:
  build: .
  command: python index-worker.py
  volumes:
   - .:/code
  links:
   - redis
dashboard:
  build: .
  command: rq-dashboard -u redis -P 6379
  links:
   - redis
  ports:
   - "5002:9181"
redis:
  image: redis
  ports:
    - "5001:6379"

